### PR TITLE
.env added. added env-cmd package.

### PR DESCRIPTION
**Pull request by JaMoLpE88**
## Description

Added .env-cmdrc in root.
Installed env-cmd package.

Set `fe` (frontend), `be` (backend), `pro` (production) enviroments on ` .env-cmdrc`

You can now start with `start-fe`, `start-be` or `start-pro`. Same with test and build.

Login data in Slack for `fe` enviroment.

PD: README and instructions updated in f8a3d4503ee2750e8280337320b0f927241238a9

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/codevsoft/workkit/blob/master/CONTRIBUTING.md) doc document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by namelivia** [comment]
I believe this will require updating the `entrypoint` script on `docker-compose.yml` from:

```
["npx", "nx", "serve", "--host=0.0.0.0", "workkit-fe"]
```
to something like
```
["npx", "env-cmd", "fe", "nx", "serve", "--host=0.0.0.0", "workkit-fe"]
```

on both frontend and backend containers, if not I suspect env variables won't be loaded when starting the app using composer.

**Comment by JaMoLpE88** [comment]
I will do it as soon as possible 👍

**Comment by JaMoLpE88** [comment]
> I believe this will require updating the `entrypoint` script on `docker-compose.yml` from:
> 
> ```js
> ["npx", "nx", "serve", "--host=0.0.0.0", "workkit-fe"]
> ```
> 
> to something like
> 
> ```js
> ["npx", "env-cmd", "fe", "nx", "serve", "--host=0.0.0.0", "workkit-fe"]
> ```
> 
> on both frontend and backend containers, if not I suspect env variables won't be loaded when starting the app using composer.
> Also this may also require an update on the instructions on how to launch the app on the `README` file.

Enviroments and README instructions updated. 
Commit: f8a3d4503ee2750e8280337320b0f927241238a9

**Comment by namelivia** [comment]
Sorry @JaMoLpE88 I was referring to the contents of the `docker-compose.yml` file on the root folder for the project.

**Review by 73nko — APPROVED** [review]
LGTM! ✅

**Pull request merged**
